### ISSUE TITLE
Decide on Mapping API

### ISSUE THREAD

**Issue by boulderalf** [BeeSafeEarth/BeeSafeEarth#7]
Add mapping requirements here. Update how Google and Mapbox support those requirements.

| Requirement | Google Maps API | Mapbox API |
| --- | :-: | :-: |
| Render 10s of thousands of data points. Clustering? | KML Layers/Zoom Levels | ?? |
| Draw **neighborhood** outlines | Built-in "neighborhood" and "sublocality" place types | ?? |
| Draw **region** outlines | Automatic if region = county or other known boundary, otherwise must be done manually (many lat-lng points) | ?? |
| Draw **parcel** outlines | This USED TO BE free and have great coverage until a few months ago, when Google discontinued Google Earth and, with it, the Parcel Data layer | ?? |

**Comment by boulderalf** [comment]
@ZebGirouard please see the table in the initial issue description.

cc @Beesafedavid @kristinreynolds @autumnmartin

**Comment by ZebGirouard** [comment]
A note about parcel outlines...

1) As mentioned, these used to be standard issue on Google Maps until Jan 2016
2) There is a free **source** for this information, however, it won't integrate with our website Bee Map, and we can't easily scrape the data from it, [here it is](http://www.parcelatlas.com/HTML5App/index.html#map)
3) We _can_ add this data in a KML layer in GMaps, also probably in MapBox, but it would be a very manual process.

I will continue investigating, but I'm not expecting an easy solution.

**Comment by Beesafedavid** [comment]
Ouch! Good luck.

> On Apr 12, 2016, at 8:03 AM, Timothy Zeb Girouard notifications@github.com wrote:
> 
> A note about parcel outlines...
> 
> 1) As mentioned, these used to be standard issue on Google Maps until Jan 2016
> 2) There is a free source for this information, however, it won't integrate with our website Bee Map, and we can't easily scrape the data from it, here it is http://www.parcelatlas.com/HTML5App/index.html#map
> 3) We can add this data in a KML layer in GMaps, also probably in MapBox, but it would be a very manual process.
> 
> I will continue investigating, but I'm not expecting an easy solution.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub https://github.com/BeeSafeEarth/BeeSafeEarth/issues/7#issuecomment-208922633

=== David Wheeler, Kansuke II ===
Musician (Shakuhachi) + Musicologist
3660 Buckeye Ct., Boulder, CO 80304 USA
shakudavid@gmail.com  
Cell: 720-545-5595
www.kansuke2.com http://www.kansuke2.com/

**Comment by ZebGirouard** [comment]
And now for my neighborhood research, while it is true that Google Maps has a pretty good repository of neighborhoods, it is far from complete, and pretty overlappy.  To make matters worse, while it looks nice and pretty on a standard Google Map, this data (namely, the boundary data) is not available from any Google API at the moment.  _Sad tuba_

There is a glimmer of hope from the [Zillow Neighborhood Boundaries](http://www.zillow.com/howto/api/neighborhood-boundaries.htm) file.  However, this data is a few years old, and the "neighborhoods" are pretty darned large.  Let me know if I'm crazy, but there are more than 9 neighborhoods in Boulder.  See outlines below:

![screenshot 2016-04-13 at 12 19 51 pm](https://cloud.githubusercontent.com/assets/5480464/14504443/16787b68-0172-11e6-8614-ab10acc73386.png)

There is a paid option called [Maponics](http://www.maponics.com/products/communities/neighborhood-boundaries) that comes highly recommended by developers on fora.  

I'm wondering if our best strategy would be something like using Google My Maps to let people create boundaries (just drop a few pins), export to KML, then import that to a master neighborhood boundaries file.  It would require a few things:

1) A few step-by-step instructions
2) Involved and tech-savvyish people who'd feel comfortable doing this
3) Some sort of script to handle importing the KML submissions

**Comment by boulderalf** [comment]
@ZebGirouard my vote is to provide a function that lets neighborhood Bee Safe leaders create their own boundaries.

**Comment by Beesafedavid** [comment]
I agree with Alfred. 
It could be a mix of actions, but ascribing a location and then leaving it up to the locals to do the naming is actually quite strong. It gives them ownership.
FYI, Boulder has about 60 named neighborhoods (and we just got a city NH Liaison; where will that go?), but I don’t think Melody-Catalpa is one of them, since we named it ourselves (which was quite a big deal, and fun!).

Heading off to Beyond Pesticides Forum in Portland tomorrow. Bzzzzzzz
Cheers,
david

> On Apr 13, 2016, at 12:37 PM, Alfred Sawatzky notifications@github.com wrote:
> 
> @ZebGirouard https://github.com/ZebGirouard my vote is to provide a function that lets neighborhood Bee Safe leaders create their own boundaries.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub https://github.com/BeeSafeEarth/BeeSafeEarth/issues/7#issuecomment-209587659

=== David Wheeler, Kansuke II ===
Musician (Shakuhachi) + Musicologist
3660 Buckeye Ct., Boulder, CO 80304 USA
shakudavid@gmail.com  
Cell: 720-545-5595
www.kansuke2.com http://www.kansuke2.com/

**Comment by Beesafedavid** [comment]
Would there be a way to automate the naming process, so that a coder need not be involved? Perhaps a form suggesting the area, and requesting the local pledger or BSN coordinator to use the local name.

BTW, Melody-Catalpa is from the two largest parks in the Melody Heights development subdivision, which was named after the daughter of the developer (my claims for naming after the musicality of its residents notwithstanding).

> On Apr 13, 2016, at 8:23 PM, David Wheeler <shakudavid@gmail.com <mailto:shakudavid@gmail.com>> wrote:
> 
> I agree with Alfred. 
> It could be a mix of actions, but ascribing a location and then leaving it up to the locals to do the naming is actually quite strong. It gives them ownership.
> FYI, Boulder has about 60 named neighborhoods (and we just got a city NH Liaison; where will that go?), but I don’t think Melody-Catalpa is one of them, since we named it ourselves (which was quite a big deal, and fun!).
> 
> Heading off to Beyond Pesticides Forum in Portland tomorrow. Bzzzzzzz
> Cheers,
> david
> 
> > On Apr 13, 2016, at 12:37 PM, Alfred Sawatzky <notifications@github.com <mailto:notifications@github.com>> wrote:
> > 
> > @ZebGirouard https://github.com/ZebGirouard my vote is to provide a function that lets neighborhood Bee Safe leaders create their own boundaries.
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub https://github.com/BeeSafeEarth/BeeSafeEarth/issues/7#issuecomment-209587659
> 
> === David Wheeler, Kansuke II ===
> Musician (Shakuhachi) + Musicologist
> 3660 Buckeye Ct., Boulder, CO 80304 USA
> shakudavid@gmail.com mailto:shakudavid@gmail.com  
> Cell: 720-545-5595
> www.kansuke2.com http://www.kansuke2.com/

=== David Wheeler, Kansuke II ===
Musician (Shakuhachi) + Musicologist
3660 Buckeye Ct., Boulder, CO 80304 USA
shakudavid@gmail.com mailto:shakudavid@gmail.com  
Cell: 720-545-5595
www.kansuke2.com http://www.kansuke2.com/

**Comment by ZebGirouard** [comment]
Hm, the problem is where to get the names and/or locations from.  It seems to me that there are no "standard" definitions for either of these things, on MapBox or GoogleMaps, and the only free source for this info is Zillow which defines neighborhoods more like boroughs and is out-of-date.  

The naming part can be "automated" in the sense that we could have a form for it and a step-by-step process on a webpage to add it.  

The location part is trickier, as we will need some sort of manual input to define the borders.  Perhaps we can embed a My Maps screen in a Bee Safe Earth page, instead of leading them offsite. And we could have a required Borders text field below to at least give us some inkling of boundaries if the points are all over the place.

I don't know, it'll be messy.  The silver lining is that the people doing these submissions, or at least the filtering, will be coordinators, so they'll be more careful and will be a smaller population to cater to if things go wrong.

**Comment by boulderalf** [comment]
We have decided to use Google Maps API.  Closing this ticket.
